export const INDUSTRIES = [
  'Accounting',
  'Agriculture',
  'Airlines/Aviation',
  'Automotive',
  'Banking',
  'Biotechnology',
  'Broadcasting',
  'Building Materials',
  'Chemicals',
  'Civil Engineering',
  'Computer Hardware',
  'Computer Software',
  'Construction',
  'Consulting',
  'Consumer Electronics',
  'Consumer Goods',
  'Consumer Services',
  'Cosmetics',
  'Education',
  'Electrical/Electronic Manufacturing',
  'Energy',
  'Engineering',
  'Entertainment',
  'Environmental Services',
  'Events Services',
  'Facilities Services',
  'Fashion',
  'Financial Services',
  'Food & Beverages',
  'Food Production',
  'Furniture',
  'Government',
  'Healthcare',
  'Hospitality',
  'Human Resources',
  'Import/Export',
  'Information Services',
  'Information Technology',
  'Insurance',
  'Internet',
  'Investment Banking',
  'Legal Services',
  'Logistics',
  'Luxury Goods',
  'Machinery',
  'Management Consulting',
  'Manufacturing',
  'Marketing',
  'Media Production',
  'Medical Devices',
  'Mining',
  'Oil & Energy',
  'Packaging',
  'Pharmaceuticals',
  'Professional Services',
  'Public Relations',
  'Publishing',
  'Real Estate',
  'Restaurants',
  'Retail',
  'Security',
  'Semiconductors',
  'Shipping',
  'Sports',
  'Telecommunications',
  'Textiles',
  'Think Tanks',
  'Tobacco',
  'Tourism',
  'Translation',
  'Transportation',
  'Utilities',
  'Warehousing',
  'Wholesale',
  'Wine & Spirits',
  'Wireless',
] as const;

export type Industry = typeof INDUSTRIES[number];
